eval_freq: 1 
train_id: save-forward-2patch-upsample
total_epochs: 100
use_wandb: True

lr: 0.0002

sig_max: 0.1 
sig_min: 0.001 
noise_sig: 25 

train_data_path: '/home/ac2323/4782/Noise2Score-Reproduce/DIV2K_train_HR' 
eval_data_path: '/home/ac2323/4782/Noise2Score-Reproduce/DIV2K_valid_HR'
peak: 255
patch_num: 2